### ISSUE TITLE
some problem for method 

### ISSUE THREAD

**Issue by SakuBorder** [cangumeli/ObjectMatch#3]
Very good job! But I have some questions about the response you gave me. I want to know which part is crucial for implementing Overlap? And what role does object identification play in this task?

**Comment by cangumeli** [comment]
Thanks for your interest in our project.

Object identification is necessary because otherwise you cannot associate objects and get correspondences. I don't know what you mean by implementing overlap, but I would be happy to help if you elaborate.

Also, since this is not an issue regarding the codebase, I am closing the issue for now. Could you reach out to me through email? My profile and email are here. https://www.niessnerlab.org/members/can_guemeli/profile.html .
